### ISSUE TITLE
Redirects to locations with invalid characters

### ISSUE THREAD

**Issue by smashwilson** [deconst/presenter#138]
When a redirect is performed for a presented URL that contains URL-encoded characters, it appears to attempt to redirect with the URL-decoded form instead:

```
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
    at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:718:10)
    at ServerResponse.location (/usr/src/app/node_modules/express/lib/response.js:835:8)
    at ServerResponse.redirect (/usr/src/app/node_modules/express/lib/response.js:874:8)
    at /usr/src/app/src/server/rewrites.js:33:18
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:312:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:271:10)
```

Sample URL: `/knowledge_center/video/sharepoint-2010-managed-metadata-service-application-%e2%80%93-part-3`

**Comment by smashwilson** [comment]
Related:

```
URIError: Failed to decode param 'knowledge_center/case-study/domino%e2%c3%83%c6%92%c3%86%e2%80%99%c3%83%e2%80%9a%c3%82%c2%af%c3%83%c6%92%c3%a2%e2%82%ac%c5%a1%c3%83%e2%80%9a%c3%82%c2%bf%c3%83%c6%92%c3%a2%e2%82%ac%c5%a1%c3%83%e2%80%9a%c3%82%c2%bd%c3%83%c6%92%c3%86%e2%80%99%c3%83%e2%80%9a%c3%82%c2%af%c3%83%c6%92%c3%a2%e2%82%ac%c5%a1%c3%83%e2%80%9a%c3%82%c2%bf%c3%83%c6%92%c3%a2%e2%82%ac%c5%a1%c3%83%e2%80%9a%c3%82%c2%bds-uk-embraces-hybrid-portfolio'
    at decodeURIComponent (native)
    at decode_param (/usr/src/app/node_modules/express/lib/router/layer.js:167:12)
    at Layer.match (/usr/src/app/node_modules/express/lib/router/layer.js:143:15)
    at matchLayer (/usr/src/app/node_modules/express/lib/router/index.js:557:18)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:216:15)
    at /usr/src/app/src/server/rewrites.js:43:5
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:312:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:330:12)
```
