### ISSUE TITLE
Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by smashwilson** [deconst/presenter#19]
I'm getting a stack trace when content isn't found and the control repository doesn't define a custom error page:

```
presenter_1 | /usr/src/app/src/content.js:154
presenter_1 |         if(response.statusCode !== 200 || result.error) {
presenter_1 |                    ^
presenter_1 | TypeError: Cannot read property 'statusCode' of undefined
presenter_1 |     at /usr/src/app/src/content.js:154:20
presenter_1 |     at Request._callback (/usr/src/app/src/content.js:125:7)
presenter_1 |     at Request.self.callback (/usr/src/app/node_modules/request/request.js:344:22)
presenter_1 |     at Request.emit (events.js:110:17)
presenter_1 |     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1239:14)
presenter_1 |     at Request.emit (events.js:129:20)
presenter_1 |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1187:12)
presenter_1 |     at IncomingMessage.emit (events.js:129:20)
presenter_1 |     at _stream_readable.js:908:16
presenter_1 |     at process._tickCallback (node.js:355:11)
```

It also looks like it's requesting a 500 instead of a 404 for "missing metadata envelope":

```
presenter_1 | 2015-04-16T13:58:08.487Z - verbose: Handling presented URL [https://developer.rackspace.com/].
presenter_1 | 2015-04-16T13:58:08.487Z - debug: Mapping service request: [http://mapping:8080/at/https%3A%2F%2Fdeveloper.rackspace.com%2F]
presenter_1 | 2015-04-16T13:58:08.493Z - debug: Mapping service response: success => [https://github.com/smashwilson/deconst-drc-blog]
presenter_1 | 2015-04-16T13:58:08.493Z - debug: Content service request: [http://content:8080/content/https%3A%2F%2Fgithub.com%2Fsmashwilson%2Fdeconst-drc-blog]
presenter_1 | 2015-04-16T13:58:08.604Z - error: ServerError: Error: No content found for content ID [https://github.com/smashwilson/deconst-drc-blog]
presenter_1 | 2015-04-16T13:58:08.605Z - debug: Error layout page request: [http://layout:8080/error/https%3A%2F%2Fdeveloper.rackspace.com%2F/500]
```

**Comment by smashwilson** [comment]
It looks like my presenter container image is out of date:

```
ashl6947@MMN1F3FD58 ~/code/deconst-drc-control (master=) $ curl -s http://docker/version | python -m json.tool
{
    "commit": "4156083",
    "service": "presenter",
    "version": "1.0.0"
}
```

**Comment by smashwilson** [comment]
Er, no, that's right. My local clone was out of date.
